"""The contract cannot drift from the implementation without the build saying so.

Python is the reference implementation, and the artifacts under contract/ are what
every port is written and verified against. A contract regenerated by hand, or not
regenerated at all, silently turns a port's passing suite into a lie. These tests
are the mechanism that makes "derived, never hand-maintained" true rather than an
intention stated in a document.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO_ROOT / "python" / "tools"

if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

import export_conformance  # noqa: E402
import export_contract  # noqa: E402


def test_the_tool_surface_contract_is_current() -> None:
    assert export_contract.main(["--check"]) == 0, (
        "The tool surface changed. Regenerate with "
        "`python tools/export_contract.py`, then port the change to every other "
        "implementation in this repository."
    )


def test_the_conformance_corpus_is_current() -> None:
    assert export_conformance.main(["--check"]) == 0, (
        "The conformance corpus changed. Regenerate with "
        "`python tools/export_conformance.py`."
    )


def test_the_contract_records_the_upstream_versions_actually_in_use() -> None:
    """The Python implementation tracks upstream; ports track Python. A contract
    that did not say which upstream it reflects would leave a port unable to tell
    whether it is behind."""
    contract = export_contract.build_contract()
    upstream = contract["generated_with"]["upstream"]
    assert set(upstream) == set(export_contract.UPSTREAM)
    for distribution, version in upstream.items():
        assert version != "not installed" or distribution == "pyvbaharness", (
            f"{distribution} is not installed, so the contract cannot describe this build"
        )


def test_every_tool_declares_whether_it_writes() -> None:
    """A client that gates writes behind a confirmation reads these hints, so a
    tool that lied about them would be confirmed by nobody."""
    contract = export_contract.build_contract()
    for tool in contract["tools"]:
        annotations = tool["annotations"]
        assert not (annotations["read_only"] and annotations["destructive"]), (
            f"{tool['name']} claims to be both read-only and destructive"
        )
        if tool["name"].split("_")[1] in {"write", "delete", "rename", "create", "edit"}:
            assert not annotations["read_only"], (
                f"{tool['name']} changes something and must not be marked read-only"
            )


def test_every_tool_has_a_description_an_agent_can_act_on() -> None:
    contract = export_contract.build_contract()
    for tool in contract["tools"]:
        assert len(tool["description"]) > 80, f"{tool['name']} is under-described"
        for name, schema in tool["input_schema"].get("properties", {}).items():
            assert schema.get("description"), (
                f"{tool['name']}.{name} has no description, so a caller has to guess"
            )


def test_the_conformance_corpus_only_names_tools_that_exist() -> None:
    contract = export_contract.build_contract()
    known = {tool["name"] for tool in contract["tools"]}
    corpus = export_conformance.build()
    for case in corpus["cases"]:
        for step in case["steps"]:
            assert step["tool"] in known, (
                f"{case['id']} calls {step['tool']}, which is not in the tool surface"
            )
